"""Orchestrator: the full pipeline for one user turn.

    user message
        -> Router (LLM, structured JSON)          which tool(s), which language
        -> ToolBox (data-driven tools)            links / onboarding steps / RAG search
        -> Answer LLM (grounded in tool context)  reply in the user's language
        -> Guardrails                             real links only, required links present

Every reply, including link and step replies, is generated by the LLM from
retrieved/tool context (RAG). Two deterministic guardrails sit after generation
because a small model can still drop or invent a URL.

If the answer model is unreachable the user still gets the retrieved text, so
the assistant degrades to an extractive answer instead of failing. There is no
keyword routing anywhere.
"""
import re
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

import config
from knowledge import Page
from llm import LLMError, OllamaClient
from router import Router, RouterDecision
from system_prompt import answer_system_prompt, answer_user_prompt
from tools import ToolBox, ToolResult

_URL = re.compile(r"(?:https?://|(?<![\w.])lms\.ncair\.nitda\.gov\.ng|(?<![\w.])ncair\.nitda\.gov\.ng)[^\s)\]>\"']*", re.I)


def _norm_url(u: str) -> str:
    u = u.strip().rstrip(".,;:!?)").lower()
    u = re.sub(r"^https?://", "", u)
    return u.rstrip("/")


@dataclass
class Reply:
    text: str
    language: str = "en"
    decision: Optional[RouterDecision] = None
    results: List[ToolResult] = field(default_factory=list)
    removed_urls: List[str] = field(default_factory=list)
    added_links: List[str] = field(default_factory=list)
    answer_fallback: bool = False
    answer_model: str = ""
    timings: Dict[str, float] = field(default_factory=dict)

    @property
    def tool_calls(self) -> List[Dict]:
        return self.decision.calls if self.decision else []

    @property
    def sources(self) -> List[str]:
        out: List[str] = []
        for r in self.results:
            for s in r.sources:
                if s not in out:
                    out.append(s)
        return out

    def debug(self) -> str:
        d = self.decision
        return (
            f"language={self.language} router_fallback={d.fallback if d else None} "
            f"answer_model={self.answer_model} calls={self.tool_calls} sources={self.sources} answer_fallback={self.answer_fallback} "
            f"removed_urls={self.removed_urls} added_links={self.added_links} timings={self.timings}"
        )


class Assistant:
    def __init__(self, router_llm=None, answer_llm=None, toolbox: Optional[ToolBox] = None,
                 multilingual_llm=None):
        self.tb = toolbox or ToolBox()
        self.router_llm = router_llm or OllamaClient(config.ROUTER_MODEL)
        self.answer_llm = answer_llm or OllamaClient(config.ANSWER_MODEL)
        # Optional specialist for Hausa/Yoruba/Igbo answers (N-ATLaS). None = disabled.
        if multilingual_llm is None and config.MULTILINGUAL_MODEL and config.MULTILINGUAL_MODEL != config.ANSWER_MODEL:
            multilingual_llm = OllamaClient(config.MULTILINGUAL_MODEL)
        self.multilingual_llm = multilingual_llm
        self._multi_checked_at = -1e9
        self._multi_ok = False
        self.router = Router(self.router_llm, self.tb)
        self.all_urls = {_norm_url(p.url) for p in self.tb.pages.values()}

    # ------------------------------------------------- model selection
    def _multilingual_available(self) -> bool:
        """Is the specialist model installed? Re-checked every 60 s so installing it needs no restart."""
        if self.multilingual_llm is None:
            return False
        if time.monotonic() - self._multi_checked_at > 60:
            check = getattr(self.multilingual_llm, "is_available", None)
            self._multi_ok = bool(check()) if check else True
            self._multi_checked_at = time.monotonic()
        return self._multi_ok

    def _llms_for(self, language: str):
        """Models to try, in order, for writing the answer."""
        if language in config.MULTILINGUAL_LANGS and self._multilingual_available():
            return [self.multilingual_llm, self.answer_llm]
        return [self.answer_llm]

    # ---------------------------------------------------------------- API
    def reply(self, query: str, history: Optional[List[Dict[str, str]]] = None) -> Reply:
        t0 = time.perf_counter()
        decision = self.router.route(query, history)
        t1 = time.perf_counter()

        results = [self.tb.execute(c["tool"], {k: v for k, v in c.items() if k != "tool"}) for c in decision.calls]
        t2 = time.perf_counter()

        context = "\n\n=====\n\n".join(r.context for r in results)
        out = Reply(text="", language=decision.language, decision=decision, results=results)
        messages = [{"role": "system", "content": answer_system_prompt(self.tb.pages, decision.language)}]
        messages += (history or [])[-2 * config.HISTORY_TURNS:]
        messages.append({"role": "user", "content": answer_user_prompt(query, decision.english_query, context)})
        text = ""
        for llm in self._llms_for(decision.language):  # specialist first (if any), then the default
            try:
                text = llm.chat(messages, options=config.ANSWER_OPTIONS)
                if text.strip():
                    out.answer_model = getattr(llm, "model", "")
                    break
            except LLMError:
                continue
        if not text.strip():
            out.answer_fallback = True
            text = self._extractive_answer(results)
        t3 = time.perf_counter()

        out.text = self._guard_links(text, results, context, out)
        out.timings = {"route_s": round(t1 - t0, 2), "tools_s": round(t2 - t1, 2),
                       "answer_s": round(t3 - t2, 2), "total_s": round(time.perf_counter() - t0, 2)}
        return out

    # --------------------------------------------------------- guardrails
    def _guard_links(self, text: str, results: List[ToolResult], context: str, out: Reply) -> str:
        allowed = set(self.all_urls) | {_norm_url(u) for u in _URL.findall(context)}
        for m in sorted(set(_URL.findall(text)), key=len, reverse=True):
            if _norm_url(m) not in allowed:
                text = text.replace(m, "").strip()
                out.removed_urls.append(m)
        needed: List[Page] = []
        for r in results:
            for p in r.links:
                if p not in needed:
                    needed.append(p)
        for p in needed[:2]:
            if _norm_url(p.url) not in {_norm_url(u) for u in _URL.findall(text)}:
                text = f"{text.rstrip()}\n\n🔗 {p.title}: {p.url}"
                out.added_links.append(p.url)
        return text

    # ----------------------------------------------------------- offline
    @staticmethod
    def _extractive_answer(results: List[ToolResult]) -> str:
        if not results:
            return "Hello! I can help with NCAIR LMS registration steps, course rules and portal links. What do you need?"
        parts = ["(The language model is not reachable, so here is the relevant text from the official documents.)"]
        for r in results:
            if not r.ok:
                parts.append("I could not complete that lookup right now. Please ask an NCAIR staff member at the hall.")
            elif r.abstain:
                parts.append("I don't have that information. Please ask an NCAIR staff member at the hall.")
            elif r.tool == "get_portal_link":
                parts.append(r.context.replace("PAGE: ", "").replace("\nURL: ", ": ").split("\nABOUT:")[0])
            else:
                parts.append(re.sub(r"^RETRIEVAL CONFIDENCE:.*?\n\n", "", r.context, flags=re.S))
        return "\n\n".join(parts)


_default: Optional[Assistant] = None


def agentic_rag_orchestrator_v3(user_query: str, history=None) -> str:
    """Convenience entry point (same role the v2 function had)."""
    global _default
    if _default is None:
        _default = Assistant()
    return _default.reply(user_query, history).text


if __name__ == "__main__":
    a = Assistant()
    for q in ["Where do I sign in?", "I'm stuck on step 4", "What is the minimum attendance?", "hi there"]:
        r = a.reply(q)
        print(f"\nQ: {q}\nA: {r.text}\n   [{r.debug()}]")
